name: Push to ECR

on: push
jobs:
  build:

    name: Push to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Docker build
      run: docker build --tag cashier-docs:latest .

    - name: Push to registry
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: eu-west-3
        image: cashier-docs:latest
