name: Elixir CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim

    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v1

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Run Format
      run: mix format --check-formatted

    - name: Run Tests
      run: mix test

    - name: Run Dialyzer
      run: mix dialyzer

    - name: Run Coveralls
      run: mix coveralls.github
